root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/mobicode"
  args_bin = ["serve"]
  entrypoint = "./tmp/server"
  delay = 1000
  exclude_dir = ["data", "docs", "mobile", "tmp", "vendor", "yaak"]
  include_ext = ["go", "graphqls", "yml"]
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
