package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/soumajitgh/mobicode/internal/graphql/generated"
	authctx "github.com/soumajitgh/mobicode/internal/graphql/middleware"
	"github.com/soumajitgh/mobicode/internal/graphql/model"
	"github.com/soumajitgh/mobicode/internal/pairing"
	"github.com/soumajitgh/mobicode/internal/store/repository"
)

// CreateDevicePairing is the resolver for the createDevicePairing field.
func (r *mutationResolver) CreateDevicePairing(ctx context.Context) (*model.DevicePairing, error) {
	identity := authctx.FromContext(ctx)
	if identity.AuthError != nil {
		return nil, coded("INTERNAL_ERROR", "authentication failed")
	}
	if identity.MobileUser != nil {
		return nil, coded("FORBIDDEN", "web authentication required")
	}
	if identity.WebUser == nil {
		return nil, coded("UNAUTHENTICATED", "web authentication required")
	}
	p, err := r.Pairing.Create(ctx, identity.WebUser.ID)
	if err != nil {
		if errors.Is(err, pairing.ErrAddressUnavailable) {
			return nil, coded("SERVER_ADDRESS_UNAVAILABLE", err.Error())
		}
		return nil, coded("INTERNAL_ERROR", "could not create pairing")
	}
	return &model.DevicePairing{ID: p.ID, QRPayload: p.QRPayload, ExpiresAt: p.ExpiresAt}, nil
}

// ClaimDevicePairing is the resolver for the claimDevicePairing field.
func (r *mutationResolver) ClaimDevicePairing(ctx context.Context, input model.ClaimDevicePairingInput) (*model.MobileSession, error) {
	if input.Device == nil {
		return nil, coded("VALIDATION_FAILED", "device is required")
	}
	session, err := r.Pairing.Claim(ctx, input.Token, input.Device.Name, string(input.Device.Platform))
	if err != nil {
		switch {
		case errors.Is(err, repository.ErrInvalidPairing):
			return nil, coded("INVALID_PAIRING_TOKEN", "invalid pairing token")
		case errors.Is(err, repository.ErrExpiredPairing):
			return nil, coded("PAIRING_EXPIRED", "pairing expired")
		case errors.Is(err, repository.ErrClaimedPairing):
			return nil, coded("PAIRING_ALREADY_CLAIMED", "pairing already claimed")
		case errors.Is(err, pairing.ErrValidation):
			return nil, coded("VALIDATION_FAILED", "invalid device metadata")
		default:
			return nil, coded("INTERNAL_ERROR", "could not claim pairing")
		}
	}
	device := &model.MobileDevice{ID: session.Device.ID, Name: session.Device.Name, Platform: model.DevicePlatform(session.Device.Platform), CreatedAt: session.Device.CreatedAt}
	return &model.MobileSession{AccessToken: session.AccessToken, User: graphUser(session.User), Device: device}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
