package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"strings"

	"github.com/soumajitgh/mobicode/internal/graphql/generated"
	"github.com/soumajitgh/mobicode/internal/graphql/model"
	"github.com/soumajitgh/mobicode/internal/service/task"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	result, err := r.TaskService.Create(ctx, task.CreateInput{Title: input.Title})
	if err != nil {
		return nil, err
	}
	return mapTask(result), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	taskID, err := parseTaskID(id)
	if err != nil {
		return nil, err
	}
	var status *string
	if input.Status != nil {
		value := strings.ToLower(input.Status.String())
		status = &value
	}
	result, err := r.TaskService.Update(ctx, taskID, task.UpdateInput{Title: input.Title, Status: status})
	if err != nil {
		return nil, err
	}
	return mapTask(result), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	taskID, err := parseTaskID(id)
	if err != nil {
		return false, err
	}
	if err := r.TaskService.Delete(ctx, taskID); err != nil {
		return false, err
	}
	return true, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	taskID, err := parseTaskID(id)
	if err != nil {
		return nil, err
	}
	result, err := r.TaskService.Get(ctx, taskID)
	if err != nil {
		return nil, err
	}
	return mapTask(result), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, first *int, after *string) (*model.TaskConnection, error) {
	firstValue := 20
	if first != nil {
		firstValue = *first
	}
	result, err := r.TaskService.List(ctx, task.ListInput{First: firstValue, After: after})
	if err != nil {
		return nil, err
	}
	nodes := make([]*model.Task, 0, len(result.Nodes))
	for i := range result.Nodes {
		nodes = append(nodes, mapTask(&result.Nodes[i]))
	}
	return &model.TaskConnection{Nodes: nodes, PageInfo: &model.PageInfo{HasNextPage: result.HasNextPage, EndCursor: result.EndCursor}}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
