package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/soumajitgh/mobicode/internal/graphql/generated"
	authctx "github.com/soumajitgh/mobicode/internal/graphql/middleware"
	"github.com/soumajitgh/mobicode/internal/graphql/model"
)

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model.User, error) {
	identity := authctx.FromContext(ctx)
	if identity.AuthError != nil {
		return nil, coded("INTERNAL_ERROR", "authentication failed")
	}
	if identity.InvalidBearer {
		return nil, coded("INVALID_ACCESS_TOKEN", "invalid mobile access token")
	}
	if identity.MobileUser == nil {
		return nil, nil
	}
	return graphUser(*identity.MobileUser), nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
