package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/soumajitgh/mobicode/graphql/generated"
	"github.com/soumajitgh/mobicode/graphql/model"
	"github.com/soumajitgh/mobicode/internal/auth"
)

// Viewer returns the one identity configured for this deployment.
func (r *queryResolver) Viewer(ctx context.Context) (*model.Identity, error) {
	if _, ok := auth.PrincipalFromContext(ctx); !ok {
		return nil, auth.ErrUnauthenticated
	}
	owner, err := r.owner.Owner(ctx)
	if err != nil {
		return nil, err
	}
	return &model.Identity{PublicKey: owner.PublicKey, CreatedAt: owner.CreatedAt}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
