package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/soumajitgh/mobicode/graphql/model"
	"github.com/soumajitgh/mobicode/internal/auth"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return r.user.User(ctx, id)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	principal, ok := auth.PrincipalFromContext(ctx)
	if !ok {
		return nil, auth.ErrUnauthenticated
	}
	u, err := r.user.User(ctx, principal.UserID)
	if err != nil {
		return nil, err
	}
	if u == nil {
		return nil, auth.ErrUnauthenticated
	}
	return u, nil
}
